---
title: "R Notebook"
output: html_notebook
---



```{r}
library(dplyr)
library(lubridate)
```

```{r}
date1 <- c("01-01-2022", "02-01-2022", "01-02-2022", "02-02-2022")
date2 <- c("15-01-2022", "13-02-2022", "", "20-02-2022")
ot <- c("MI", "FA", "SOL", "LA")

df <- data.frame(date2, date1, ot)

difftime(as.Date(date1), as.Date(date2), units = "weeks")

date1a <- as.POSIXct(date1)



date2 <- ifelse(is.na(date2), "",
  as.POSIXct(as.POSIXct(date2, format = "%d-%m-%y"))
)

date1 <- ifelse(is.na(date1), "",
  as.POSIXct(as.POSIXct(date1, format = "%d-%m-%y"))
)

date3
```


```{r}

library(lubridate)
library(dplyr)

date1 <- c("01-01-2022", "02-01-2022", "01-02-2022", "02-02-2022")
date2 <- c("15-01-2022", "13-02-2022", "", "20-02-2022")
ot <- c("MI", "FA", "SOL", "LA")

df <- data.frame(date2, date1, ot)


df2 <- df %>%
  mutate(
    date1 = ifelse(is.na(date1), "",
      (as.POSIXct(date1, format = "%d-%m-%Y"))
    ),
    date2 = ifelse(is.na(date2), "",
      (as.POSIXct(date2, format = "%d-%m-%Y"))
    ),
    date3 = ifelse(date2 == "", "", (date2 - date1)) # This gives time difference in seconds
  )
```

```{r}
df <-
  groom.prox.DSCI %>%
  group_by(monkey.id, groupyear) %>%
  mutate()
(
  partner.rank <- rank(DSCI, ties.method = "average") # or which ever tie method you prefer
) %>%
  ungroup()
```

```{r}

numbers <- c(10, 105, 66, 4, 12, 46, 112)

names <- c("red", "blue", "blue", "red", "yellow", "red", "blue")

shapes <- c("circle", "circle", "square", "star", "square", "circle", "star")

example_dataframe <- data.frame(numbers, names, shapes)

df <- example_dataframe

df %>%
  head() %>%
  as.data.frame()

df <- df %>% mutate(
  "numbers_rank" = dense_rank(desc(numbers))
)
```


```{r}
library(dplyr)

df2 <-
  df %>%
  group_by(names) %>%
  mutate(
    rank = order(order(rank(numbers, ties.method = "average"), decreasing = TRUE))
  ) %>%
  filter(names == "blue") %>%
  ungroup()
```

Link: https://community.rstudio.com/t/ranking-numeric-data-for-each-individual-in-a-group-year/138589/7


```{r}
df <- structure(list(groupyear = c(
  "F2010", "F2010", "F2010", "F2010",
  "F2010", "F2010", "F2010", "F2010", "F2010", "F2010", "F2010",
  "F2010", "F2010", "F2010", "F2010", "F2010", "F2010", "F2010",
  "F2010", "F2010"
), monkey.id = c(
  "00J", "00J", "00J", "00J",
  "00J", "00J", "00J", "00J", "00J", "00J", "00J", "00J", "00J",
  "00J", "00J", "00J", "00J", "00J", "00J", "00J"
), partner.id = c(
  "00O",
  "03J", "04N", "10S", "14I", "14L", "17C", "20F", "24B", "28J",
  "28N", "29B", "29Z", "32S", "34N", "35N", "36Z", "40L", "42L",
  "43F"
), data.year = c(
  2010L, 2010L, 2010L, 2010L, 2010L, 2010L,
  2010L, 2010L, 2010L, 2010L, 2010L, 2010L, 2010L, 2010L, 2010L,
  2010L, 2010L, 2010L, 2010L, 2010L
), current.group = c(
  "F", "F",
  "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F",
  "F", "F", "F", "F", "F"
), DCSI = c(
  0, 1.27636402820631, 0, 1.40971549383981,
  0, 0.755607504698138, 0, 0, 0, 0, 0.646924233474433, 0, 0, 0.638182014103157,
  0, 0.638182014103157, 9.14323496669351, 0.694492191818142, 0,
  0
)), row.names = c(NA, 20L), class = "data.frame")
```



```{r}

library(dplyr)

df2 <- df %>%
  group_by(monkey.id, groupyear) %>%
  mutate(
    partner.rank = order(order(rank(DCSI, ties.method = "min"), decreasing = TRUE))
  ) %>%
  filter(partner.rank < 4) %>%
  ungroup()
```

```{r}
dput(df2)
```


```{r}
library(dplyr)

df2 <- df %>%
  group_by(monkey.id, groupyear) %>%
  mutate(
    partner.rank = order(order(rank(DCSI, ties.method = "min"), decreasing = TRUE))
  ) %>%
  filter(partner.rank < 4) # keep the top 3 results
```


```{r}
df3 <- structure(list(groupyear = c(
  "F2010", "F2010", "F2010", "F2010",
  "F2010", "F2010", "F2010", "F2010", "F2010", "F2010", "F2010",
  "F2010", "F2010", "F2010", "F2010", "F2010", "F2010", "F2010",
  "F2010", "F2010"
), monkey.id = c(
  "00J", "00J", "00J", "00O",
  "00O", "00O", "03J", "03J", "03J", "04N", "04N", "04N", "10S",
  "10S", "10S", "14I", "14I", "14I", "14L", "14L"
), partner.id = c(
  "36Z",
  "62V", "63V", "44J", "55V", "90D", "61J", "62V", "00J", "17C",
  "24B", "98T", "14L", "64P", "68V", "29Z", "78T", "V36", "17C",
  "68V"
), data.year = c(
  2010L, 2010L, 2010L, 2010L, 2010L, 2010L,
  2010L, 2010L, 2010L, 2010L, 2010L, 2010L, 2010L, 2010L, 2010L,
  2010L, 2010L, 2010L, 2010L, 2010L
), current.group = c(
  "F", "F",
  "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F",
  "F", "F", "F", "F", "F"
), DCSI = c(
  9.14323496669351, 5.24727433818152,
  15.0677748544049, 13.3320473141112, 12.270117025579, 71.2592375296376,
  15.6726142511153, 3.99126543701154, 1.27636402820631, 24.5036860857084,
  7.72561755609198, 16.2382372788447, 18.5164970827263, 17.3079133497021,
  15.9792558738643, 13.8380007377055, 40.1022560899402, 15.9123236938435,
  14.3415425751191, 16.1986973817819
), kinship = c(
  "kin", "kin",
  "nonkin", "nonkin", "nonkin", "kin", "kin", "nonkin", "nonkin",
  "kin", "nonkin", "kin", "kin", "nonkin", "nonkin", "nonkin",
  "kin", "nonkin", "nonkin", "nonkin"
), partner.rank = c(
  2L, 3L,
  1L, 2L, 3L, 1L, 1L, 2L, 3L, 1L, 3L, 2L, 1L, 2L, 3L, 3L, 1L, 2L,
  3L, 2L
), nonkinpresence = c(
  "0", "0", "1", "1", "1", "0", "0",
  "1", "1", "0", "1", "0", "0", "1", "1", "1", "0", "1", "1", "1"
)), class = c("grouped_df", "tbl_df", "tbl", "data.frame"), row.names = c(
  NA,
  -20L
), groups = structure(list(monkey.id = c(
  "00J", "00O", "03J",
  "04N", "10S", "14I", "14L"
), groupyear = c(
  "F2010", "F2010",
  "F2010", "F2010", "F2010", "F2010", "F2010"
), .rows = structure(list(
  1:3, 4:6, 7:9, 10:12, 13:15, 16:18, 19:20
), ptype = integer(0), class = c(
  "vctrs_list_of",
  "vctrs_vctr", "list"
))), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -7L), .drop = TRUE))
```

```{r}
library(dplyr)

summary_df <-
  df3 %>%
  group_by(monkey.id, groupyear) %>%
  summarize(kin_count = sum(kinship == "kin"))


summary_df_alternative <-
  df3 %>%
  group_by(monkey.id, groupyear) %>%
  summarize(kin_count = sum(nonkinpresence = 0)) # or != 1
```

```{r}

Final_df <-
  merge(df3, summary_df, by = c("monkey.id", "groupyear"))
```

Link: https://community.rstudio.com/t/remove-na-out-of-plot/139071

```{r}
df <- structure(list(
  Id = c(
    1503960366, 1503960366, 1503960366, 1503960366,
    1503960366
  ), Date = structure(c(16903, 16904, 16906, 16907, 16908), class = "Date"), Weekday = structure(c(3L, 4L, 6L, 7L, 1L), .Label = c(
    "Sun",
    "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"
  ), class = c(
    "ordered",
    "factor"
  )), Calories = c(1985L, 1797L, 1745L, 1863L, 1728L),
  TotalSteps = c(13162L, 10735L, 9762L, 12669L, 9705L), TotalDistance = c(
    8.5,
    6.96999979019165, 6.28000020980835, 8.15999984741211, 6.48000001907349
  ), VeryActiveDistance = c(
    1.87999999523163, 1.57000005245209,
    2.14000010490417, 2.71000003814697, 3.19000005722046
  ), ModeratelyActiveDistance = c(
    0.550000011920929,
    0.689999997615814, 1.25999999046326, 0.409999996423721, 0.779999971389771
  ), LightlyActiveDistance = c(
    6.05999994277954, 4.71000003814697,
    2.82999992370605, 5.03999996185303, 2.50999999046326
  ), SedentaryDistance = c(
    0,
    0, 0, 0, 0
  ), VeryActiveMinutes = c(25L, 21L, 29L, 36L, 38L), ModeratelyActiveMinutes = c(13L, 19L, 34L, 10L, 20L),
  LightlyActiveMinutes = c(328L, 217L, 209L, 221L, 164L), SedentaryMinutes = c(
    728L,
    776L, 726L, 773L, 539L
  ), TotalSleepRecords = c(
    1L, 2L, 1L,
    2L, 1L
  ), TotalMinutesAsleep = c(327L, 384L, 412L, 340L, 700L), TotalTimeInBed = c(346L, 407L, 442L, 367L, 712L)
), row.names = c(
  NA,
  5L
), class = "data.frame")
```


```{r}
df2 <- structure(list(
  Id = c(
    1503960366, 1503960366, 1503960366, 1503960366,
    1503960366
  ), Date = structure(c(16903, 16903, 16903, 16903, 16904), class = "Date"), Weekday = structure(c(3L, 3L, 3L, 3L, 4L), .Label = c(
    "Sun",
    "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"
  ), class = c(
    "ordered",
    "factor"
  )), Calories = c(1985L, 1985L, 1985L, 1985L, 1797L),
  TotalSteps = c(13162L, 13162L, 13162L, 13162L, 10735L), TotalDistance = c(
    8.5,
    8.5, 8.5, 8.5, 6.96999979019165
  ), Level = structure(c(
    4L,
    3L, 2L, 1L, 4L
  ), .Label = c(
    "Sedentary", "LightlyActive",
    "ModeratelyActive", "VeryActive"
  ), class = "factor"), Distance = c(
    1.87999999523163,
    0.550000011920929, 6.05999994277954, 0, 1.57000005245209
  ),
  Minutes = c(25, 13, 328, 728, 21), TotalSleepRecords = c(
    1L,
    1L, 1L, 1L, 2L
  ), TotalMinutesAsleep = c(
    327L, 327L, 327L,
    327L, 384L
  ), TotalTimeInBed = c(346L, 346L, 346L, 346L, 407L)
), row.names = c(NA, -5L), class = c("tbl_df", "tbl", "data.frame"))
```


```{r}
ActivityLong %>% # %>% is equivalent to |>
  filter(!is.na(Level)) %>%
  ggplot(aes(x = Weekday, y = Minutes, fill = Level)) +
  geom_col(position = "dodge")
```
